
graphql:
   endpoint:
      url: https://localhost:8443/starwars/graphql
      subscriptionUrl: https://localhost:8443/starwars/graphql/subscription

spring:
   main:
      # We don't need the Netty web server to start
      web-application-type: none