# Changing the port for the GraphQL server
server:
  port: 8180

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8181/profile/me
#      introspection-client-id: clientId
#      introspection-client-secret: secret

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true